source "http://rubygems.org"

gem "rails", "3.0.0"
gem "capybara", ">= 0.3.9"
gem 'mysql'

gem "disguise", :path => '../../'

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test do
  gem 'shoulda'
  gem 'factory_girl'
  gem 'mocha'
  gem 'redgreen'
end